server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: auth-service
              uri: http://localhost:9090
              predicates:
                - Path=/auth/**
              filters:
                - CircuitBreaker=authServiceCircuitBreaker,forward:/fallback/auth

            - id: user-profile-service
              uri: http://localhost:9091
              predicates:
                - Path=/user/**
              filters:
                - CircuitBreaker=userProfileServiceCircuitBreaker,forward:/fallback/user

            - id: agent-service
              uri: http://localhost:9092
              predicates:
                - Path=/agent/**
              filters:
                - CircuitBreaker=agentServiceCircuitBreaker,forward:/fallback/agent

            - id: buyer-service
              uri: http://localhost:9093
              predicates:
                - Path=/buyer/**
              filters:
                - CircuitBreaker=buyerServiceCircuitBreaker,forward:/fallback/buyer

            - id: property-service
              uri: http://localhost:9094
              predicates:
                - Path=/property/**
              filters:
                - CircuitBreaker=propertyServiceCircuitBreaker,forward:/fallback/property

            - id: seller-service
              uri: http://localhost:9095
              predicates:
                - Path=/seller/**
              filters:
                - CircuitBreaker=sellerServiceCircuitBreaker,forward:/fallback/seller

management:
  endpoints:
    web:
      exposure:
        include: health,info