server:
  port: 9090

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5433/micro_auth_service_db}
    username: ${AUTH_DB_USERNAME:aydin}
    password: ${AUTH_DB_PASSWORD:123456!}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
